### ISSUE TITLE
PDF with incorrect title

### ISSUE THREAD

**Issue by orestesgaolin** [librecube-space/cubesat-standards-handbook#1]
Hi everyone,
I noticed that in file [structure.tex](https://github.com/librecube-space/cubesat-standards-handbook/blob/master/structure.tex) in line 473 in `hypersetup` there is a small mistake with `pdftitle` and `pdfauthor` tags. It seems that `{Author}` and `{Title}` are undefined, so pdflatex/hyperref puts these words instead of proper title (see file properties [here](http://i.imgur.com/SrvbLvQ.png)).

`\hypersetup{hidelinks,backref=true,pagebackref=true,hyperindex=true,colorlinks=false,breaklinks=true,urlcolor= ocre,bookmarks=true,bookmarksopen=false,pdftitle={Title},pdfauthor={Author}}
`

I propose either to hardcode the _title_ and _author_ values there or use some global variables via `\newcommand` e.g.

`\newcommand{\bookTitle}{CubeSat Standards Handbook}`

Personally, I'd recommend using additional `setup.tex` file to gather such data e.g. title, subtitle, authors... and input it at the beginning of the `main.tex`. Let me know what you think and I can commit some of proposed changes.

**Comment by artur-scholz** [comment]
Thanks for the note. Please implement the proposed changes and submit a pull request.

**Comment by orestesgaolin** [comment]
@artur-scholz could you share your building scheme?

**Comment by artur-scholz** [comment]
@orestesgaolin : I am not all to familiar with Latex, so I simply stick to the steps as outlined in the template in main.tex:
% 1) pdflatex main
% 2) makeindex main.idx -s StyleInd.ist
% 3) biber main
% 4) pdflatex main x 2

**Comment by orestesgaolin** [comment]
@artur-scholz thank you, I'll try later if it's ok on my setup

**Comment by orestesgaolin** [comment]
@artur-scholz thanks for merging 👍 I have some more ideas to improve the overall experience with the book and will try to implement them in my spare time
